---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-rest
  labels:
    app: spring-petclinic-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic-rest
  template:
    metadata:
      labels:
        app: spring-petclinic-rest
    spec:
      containers:
        - name: petclinic
          image: springcommunity/spring-petclinic-rest
          ports:
            - name: http
              containerPort: 9966
---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-rest
  labels:
    app: spring-petclinic-rest
spec:
  selector:
    app: spring-petclinic-rest
  ports:
    - name: http
      port: 9966
      targetPort: 9966
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: spring-petclinic-rest
  labels:
    app: spring-petclinic-rest
spec:
  to:
    kind: Service
    name: spring-petclinic-rest
  port:
    targetPort: http
---
